services:
  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
    container_name: fastapi-application
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: info
      POSTGRESQL_DATABASE_URL: postgresql://admin:admin@db:5432/weather
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data: {}